try{doc("서울","강남구",4974)}catch{}
try{doc("서울","서초구",4687)}catch{}
try{doc("경기","과천시",4650)}catch{}
try{doc("서울","용산구",4002)}catch{}
try{doc("서울","성동구",3839)}catch{}
try{doc("서울","송파구",3545)}catch{}
try{doc("서울","마포구",3290)}catch{}
try{doc("서울","광진구",3248)}catch{}
try{doc("경기","성남시분당구",3049)}catch{}
try{doc("서울","동작구",3033)}catch{}
try{doc("서울","영등포구",2969)}catch{}
try{doc("서울","양천구",2897)}catch{}
try{doc("서울","중구",2738)}catch{}
try{doc("서울","강동구",2738)}catch{}
try{doc("서울","종로구",2733)}catch{}
try{doc("경기","성남시수정구",2609)}catch{}
try{doc("서울","서대문구",2602)}catch{}
try{doc("경기","하남시",2527)}catch{}
try{doc("서울","성북구",2437)}catch{}
try{doc("서울","동대문구",2384)}catch{}
try{doc("서울","강서구",2332)}catch{}
try{doc("경기","광명시",2219)}catch{}
try{doc("서울","노원구",2154)}catch{}
try{doc("서울","관악구",2137)}catch{}
try{doc("경기","성남시중원구",2040)}catch{}
try{doc("서울","은평구",2036)}catch{}
try{doc("서울","구로구",1953)}catch{}
try{doc("서울","강북구",1952)}catch{}
try{doc("서울","중랑구",1938)}catch{}
try{doc("경기","안양시동안구",1908)}catch{}
try{doc("서울","금천구",1871)}catch{}
try{doc("경기","수원시영통구",1847)}catch{}
try{doc("경기","구리시",1815)}catch{}
try{doc("서울","도봉구",1728)}catch{}
try{doc("경기","용인시수지구",1710)}catch{}
try{doc("경기","의왕시",1702)}catch{}
try{doc("세종","세종",1684)}catch{}
try{doc("대구","수성구",1560)}catch{}
try{doc("경기","안양시만안구",1521)}catch{}
try{doc("경기","화성시",1447)}catch{}
try{doc("부산","해운대구",1435)}catch{}
try{doc("인천","연수구",1404)}catch{}
try{doc("경기","수원시팔달구",1373)}catch{}
try{doc("대구","중구",1373)}catch{}
try{doc("경기","군포시",1359)}catch{}
try{doc("부산","수영구",1341)}catch{}
try{doc("경기","부천시",1331)}catch{}
try{doc("경기","고양시덕양구",1288)}catch{}
try{doc("경기","용인시기흥구",1276)}catch{}
try{doc("경기","고양시일산동구",1241)}catch{}
try{doc("경기","수원시장안구",1238)}catch{}
try{doc("경기","수원시권선구",1229)}catch{}
try{doc("경기","안산시단원구",1214)}catch{}
try{doc("부산","동래구",1210)}catch{}
try{doc("부산","연제구",1195)}catch{}
try{doc("대전","유성구",1182)}catch{}
try{doc("부산","남구",1148)}catch{}
try{doc("경기","고양시일산서구",1123)}catch{}
try{doc("경기","남양주시",1106)}catch{}
try{doc("경기","김포시",1098)}catch{}
try{doc("제주","제주시",1066)}catch{}
try{doc("부산","금정구",1053)}catch{}
try{doc("부산","서구",1032)}catch{}
try{doc("인천","부평구",1026)}catch{}
try{doc("인천","남동구",1015)}catch{}
try{doc("울산","남구",1013)}catch{}
try{doc("부산","강서구",1006)}catch{}
try{doc("경기","광주시",1005)}catch{}
try{doc("경기","시흥시",993)}catch{}
try{doc("대구","달서구",974)}catch{}
try{doc("대전","서구",974)}catch{}
try{doc("부산","부산진구",973)}catch{}
try{doc("부산","동구",973)}catch{}
try{doc("경남","창원시성산구",973)}catch{}
try{doc("경기","안산시상록구",968)}catch{}
try{doc("경남","창원시의창구",963)}catch{}
try{doc("인천","서구",939)}catch{}
try{doc("울산","중구",938)}catch{}
try{doc("경기","의정부시",921)}catch{}
try{doc("대구","남구",910)}catch{}
try{doc("광주","동구",908)}catch{}
try{doc("대구","서구",898)}catch{}
try{doc("대구","동구",894)}catch{}
try{doc("인천","중구",890)}catch{}
try{doc("경기","파주시",887)}catch{}
try{doc("제주","서귀포시",883)}catch{}
try{doc("광주","서구",881)}catch{}
try{doc("부산","북구",876)}catch{}
try{doc("광주","남구",874)}catch{}
try{doc("인천","계양구",866)}catch{}
try{doc("대구","북구",861)}catch{}
try{doc("경기","용인시처인구",852)}catch{}
try{doc("대전","중구",834)}catch{}
try{doc("충남","천안시서북구",822)}catch{}
try{doc("경기","오산시",818)}catch{}
try{doc("경기","양평군",816)}catch{}
try{doc("광주","광산구",813)}catch{}
try{doc("대구","달성군",778)}catch{}
try{doc("울산","북구",768)}catch{}
try{doc("부산","중구",764)}catch{}
try{doc("인천","미추홀구",760)}catch{}
try{doc("경기","평택시",750)}catch{}
try{doc("대전","동구",745)}catch{}
try{doc("경북","군위군",743)}catch{}
try{doc("부산","기장군",742)}catch{}
try{doc("인천","동구",736)}catch{}
try{doc("울산","울주군",735)}catch{}
try{doc("전남","여수시",731)}catch{}
try{doc("경기","이천시",728)}catch{}
try{doc("부산","영도구",715)}catch{}
try{doc("부산","사상구",715)}catch{}
try{doc("부산","사하구",712)}catch{}
try{doc("광주","북구",702)}catch{}
try{doc("전북","전주시덕진구",700)}catch{}
try{doc("경기","양주시",694)}catch{}
try{doc("전남","완도군",686)}catch{}
try{doc("울산","동구",683)}catch{}
try{doc("경남","진주시",668)}catch{}
try{doc("경남","양산시",668)}catch{}
try{doc("전남","순천시",666)}catch{}
try{doc("경북","경산시",663)}catch{}
try{doc("대전","대덕구",650)}catch{}
try{doc("경남","김해시",649)}catch{}
try{doc("충남","아산시",648)}catch{}
try{doc("경남","창원시마산회원구",648)}catch{}
try{doc("전남","함평군",643)}catch{}
try{doc("충북","청주시흥덕구",635)}catch{}
try{doc("경남","창원시진해구",632)}catch{}
try{doc("전남","무안군",631)}catch{}
try{doc("전남","나주시",628)}catch{}
try{doc("강원","춘천시",611)}catch{}
try{doc("충남","천안시동남구",610)}catch{}
try{doc("경남","남해군",602)}catch{}
try{doc("강원","양구군",594)}catch{}
try{doc("충북","청주시청원구",589)}catch{}
try{doc("충남","홍성군",582)}catch{}
try{doc("강원","속초시",580)}catch{}
try{doc("충북","청주시상당구",577)}catch{}
try{doc("충남","계룡시",575)}catch{}
try{doc("경기","여주시",568)}catch{}
try{doc("경남","통영시",566)}catch{}
try{doc("경남","창원시마산합포구",560)}catch{}
try{doc("충남","서산시",559)}catch{}
try{doc("경북","예천군",559)}catch{}
try{doc("충북","청주시서원구",556)}catch{}
try{doc("전북","전주시완산구",555)}catch{}
try{doc("경기","가평군",554)}catch{}
try{doc("강원","강릉시",553)}catch{}
try{doc("강원","원주시",553)}catch{}
try{doc("강원","평창군",546)}catch{}
try{doc("경북","영양군",542)}catch{}
try{doc("전남","담양군",541)}catch{}
try{doc("강원","화천군",539)}catch{}
try{doc("경남","거제시",537)}catch{}
try{doc("인천","강화군",536)}catch{}
try{doc("경기","안성시",533)}catch{}
try{doc("경북","영덕군",533)}catch{}
try{doc("경북","문경시",530)}catch{}
try{doc("충남","당진시",529)}catch{}
try{doc("강원","홍천군",526)}catch{}
try{doc("경북","의성군",523)}catch{}
try{doc("경기","포천시",518)}catch{}
try{doc("충북","영동군",516)}catch{}
try{doc("경북","경주시",516)}catch{}
try{doc("경북","포항시북구",516)}catch{}
try{doc("강원","양양군",513)}catch{}
try{doc("전북","익산시",510)}catch{}
try{doc("전남","화순군",509)}catch{}
try{doc("충북","옥천군",506)}catch{}
try{doc("전남","구례군",505)}catch{}
try{doc("충북","괴산군",504)}catch{}
try{doc("경기","동두천시",502)}catch{}
try{doc("전남","해남군",501)}catch{}
try{doc("경북","성주군",500)}catch{}
try{doc("전남","강진군",499)}catch{}
try{doc("전북","무주군",498)}catch{}
try{doc("경남","거창군",493)}catch{}
try{doc("경북","포항시남구",492)}catch{}
try{doc("경남","산청군",491)}catch{}
try{doc("충북","충주시",487)}catch{}
try{doc("경남","의령군",484)}catch{}
try{doc("충북","진천군",484)}catch{}
try{doc("경북","구미시",480)}catch{}
try{doc("전남","목포시",478)}catch{}
try{doc("경남","함안군",476)}catch{}
try{doc("충남","공주시",476)}catch{}
try{doc("경북","고령군",475)}catch{}
try{doc("충남","논산시",473)}catch{}
try{doc("강원","고성군",473)}catch{}
try{doc("전북","순창군",469)}catch{}
try{doc("전남","곡성군",465)}catch{}
try{doc("충남","청양군",464)}catch{}
try{doc("충남","부여군",461)}catch{}
try{doc("경북","상주시",459)}catch{}
try{doc("전북","남원시",455)}catch{}
try{doc("충남","서천군",453)}catch{}
try{doc("충남","보령시",450)}catch{}
try{doc("경남","사천시",449)}catch{}
try{doc("경남","밀양시",444)}catch{}
try{doc("전북","김제시",442)}catch{}
try{doc("경남","하동군",438)}catch{}
try{doc("충북","제천시",438)}catch{}
try{doc("강원","횡성군",435)}catch{}
try{doc("경남","고성군",432)}catch{}
try{doc("경북","울진군",431)}catch{}
try{doc("전북","군산시",427)}catch{}
try{doc("전북","임실군",427)}catch{}
try{doc("경북","안동시",425)}catch{}
try{doc("전북","정읍시",424)}catch{}
try{doc("경북","청송군",423)}catch{}
try{doc("경남","함양군",422)}catch{}
try{doc("경북","김천시",421)}catch{}
try{doc("경남","창녕군",419)}catch{}
try{doc("전북","부안군",416)}catch{}
try{doc("충남","금산군",416)}catch{}
try{doc("전남","진도군",414)}catch{}
try{doc("경북","영주시",407)}catch{}
try{doc("충북","음성군",406)}catch{}
try{doc("강원","삼척시",406)}catch{}
try{doc("전남","광양시",406)}catch{}
try{doc("강원","태백시",406)}catch{}
try{doc("강원","동해시",406)}catch{}
try{doc("충남","예산군",400)}catch{}
try{doc("전북","완주군",400)}catch{}
try{doc("전북","고창군",398)}catch{}
try{doc("전남","영광군",397)}catch{}
try{doc("충북","보은군",397)}catch{}
try{doc("전남","장흥군",394)}catch{}
try{doc("강원","영월군",391)}catch{}
try{doc("충북","단양군",389)}catch{}
try{doc("경남","합천군",389)}catch{}
try{doc("전북","장수군",380)}catch{}
try{doc("강원","인제군",377)}catch{}
try{doc("경기","연천군",376)}catch{}
try{doc("경북","영천시",373)}catch{}
try{doc("전남","고흥군",368)}catch{}
try{doc("경북","칠곡군",364)}catch{}
try{doc("전남","보성군",358)}catch{}
try{doc("강원","정선군",353)}catch{}
try{doc("충남","태안군",335)}catch{}
try{doc("강원","철원군",334)}catch{}
try{doc("경북","봉화군",327)}catch{}
try{doc("전남","장성군",310)}catch{}
try{doc("충북","증평군",305)}catch{}
try{doc("전북","진안군",279)}catch{}
try{doc("전남","영암군",277)}catch{}
try{doc("경북","청도군",250)}catch{}
